### ISSUE TITLE
Conditional hooks

### ISSUE THREAD

**Issue by jurajpiar** [RootstockCollective/dao-frontend#266]
We have some conditional execution of hooks in the `src/app/proposals/TimeRemainingColumn.tsx`.

![Screenshot 2024-10-15 at 10 08 30](https://github.com/user-attachments/assets/8d3a8d7e-546d-4162-bf63-68d5e64003e1)

I get that it is an optimisation, but this is not allowed in react. This can be seen in the error that results from this.

![Screenshot 2024-10-15 at 10 06 52](https://github.com/user-attachments/assets/cbd6f450-defc-4e2f-8b44-134d25d39f9b)

It appears to be used here as well:

<img width="766" alt="Screenshot 2024-10-15 at 10 22 12" src="https://github.com/user-attachments/assets/f5294f4d-6afe-47bd-803d-5d95dbb0bd46">

Please see https://react.dev/warnings/invalid-hook-call-warning for (dis-)allowed patterns.

**Comment by jessgusclark** [comment]
Seems to be resolved with #272.

**Comment by rodrigoncalves** [comment]
Actually it's not yet resolved. Reopening...

**Comment by jurajpiar** [comment]
> Actually it's not yet resolved. Reopening...

Indeed
![Screenshot 2024-10-29 at 19 40 05](https://github.com/user-attachments/assets/cd2263c3-4235-4224-bb62-40303bb5895b)
![Screenshot 2024-10-29 at 19 40 27](https://github.com/user-attachments/assets/65384050-6120-4d30-889f-8f5a5dcfb646)

**Comment by rodrigoncalves** [comment]
Solved here #272
