### ISSUE TITLE
Change Treasury contracts from array to object

### ISSUE THREAD

**Issue by jessgusclark** [RootstockCollective/dao-frontend#301]
This is okay for now, and I know this isn't you, but I need to mention it. I don't like these variable names with indexes, the object below should not be an array, it should be an object with a unique key and we use that unique key here.

_Originally posted by @jessgusclark in https://github.com/RootstockCollective/dao-frontend/pull/298#discussion_r1820612177_

**Comment by jessgusclark** [comment]
So this:

```ts
const treasuryContracts = [
  { name: 'Grants', address: GRANTS_BUCKET_ADDRESS },
  { name: 'Grants - Active', address: GRANTS_ACTIVE_BUCKET_ADDRESS },
  { name: 'Growth', address: GROWTH_BUCKET_ADDRESS },
  { name: 'General', address: GENERAL_BUCKET_ADDRESS },
  { name: 'Growth - Rewards', address: SIMPLIFIED_REWARD_DISTRIBUTOR_ADDRESS },
  { name: 'General', address: GENERAL_BUCKET_ADDRESS },
]
```

should be:

```ts
const treasuryContracts = {
   GRANTS: { name: 'Grants, address: ... },
   GRANTS_ACTIVE: { name: 'Grants - Active', address ... },
   ...
}

**Comment by tzinadah** [comment]
I can work on this can you assign it to me?

**Comment by jessgusclark** [comment]
@tzinadah, that would be great. Please note that our reply time to reviews right now might be a bit delayed.
